//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsEmpleados
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEmployeeSAPResponse", Namespace="http://schemas.datacontract.org/2004/07/EmpleadosSAP")]
    public partial class GetEmployeeSAPResponse : object
    {
        
        private wsEmpleados.EmployeeSAP[] EmployeeSAPField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsEmpleados.EmployeeSAP[] EmployeeSAP
        {
            get
            {
                return this.EmployeeSAPField;
            }
            set
            {
                this.EmployeeSAPField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeSAP", Namespace="http://schemas.datacontract.org/2004/07/EmpleadosSAP")]
    public partial class EmployeeSAP : object
    {
        
        private string Apellido1Field;
        
        private string Apellido2Field;
        
        private string CedulaField;
        
        private string CiudadField;
        
        private string DepartField;
        
        private string DireccionField;
        
        private string EstadoField;
        
        private string FechaField;
        
        private string Nombre1Field;
        
        private string Nombre2Field;
        
        private string PaisField;
        
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido1
        {
            get
            {
                return this.Apellido1Field;
            }
            set
            {
                this.Apellido1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido2
        {
            get
            {
                return this.Apellido2Field;
            }
            set
            {
                this.Apellido2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula
        {
            get
            {
                return this.CedulaField;
            }
            set
            {
                this.CedulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad
        {
            get
            {
                return this.CiudadField;
            }
            set
            {
                this.CiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Depart
        {
            get
            {
                return this.DepartField;
            }
            set
            {
                this.DepartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre1
        {
            get
            {
                return this.Nombre1Field;
            }
            set
            {
                this.Nombre1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre2
        {
            get
            {
                return this.Nombre2Field;
            }
            set
            {
                this.Nombre2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais
        {
            get
            {
                return this.PaisField;
            }
            set
            {
                this.PaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento
        {
            get
            {
                return this.TipoDocumentoField;
            }
            set
            {
                this.TipoDocumentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEmployeeIntranetResponse", Namespace="http://schemas.datacontract.org/2004/07/EmpleadosSAP")]
    public partial class GetEmployeeIntranetResponse : object
    {
        
        private wsEmpleados.EmployeeIntranet[] EmployeeIntranetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsEmpleados.EmployeeIntranet[] EmployeeIntranet
        {
            get
            {
                return this.EmployeeIntranetField;
            }
            set
            {
                this.EmployeeIntranetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeIntranet", Namespace="http://schemas.datacontract.org/2004/07/EmpleadosSAP")]
    public partial class EmployeeIntranet : object
    {
        
        private string AreaField;
        
        private string BirthDayField;
        
        private string CellPhoneField;
        
        private string CityField;
        
        private string EMailField;
        
        private string ExtensionField;
        
        private string FirstNameField;
        
        private string HiringDateField;
        
        private string IdNoField;
        
        private string LastNameField;
        
        private string LoginNameField;
        
        private string ManagerField;
        
        private string PhotoField;
        
        private string PositionField;
        
        private string TelephoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area
        {
            get
            {
                return this.AreaField;
            }
            set
            {
                this.AreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthDay
        {
            get
            {
                return this.BirthDayField;
            }
            set
            {
                this.BirthDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellPhone
        {
            get
            {
                return this.CellPhoneField;
            }
            set
            {
                this.CellPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail
        {
            get
            {
                return this.EMailField;
            }
            set
            {
                this.EMailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HiringDate
        {
            get
            {
                return this.HiringDateField;
            }
            set
            {
                this.HiringDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNo
        {
            get
            {
                return this.IdNoField;
            }
            set
            {
                this.IdNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName
        {
            get
            {
                return this.LoginNameField;
            }
            set
            {
                this.LoginNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manager
        {
            get
            {
                return this.ManagerField;
            }
            set
            {
                this.ManagerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo
        {
            get
            {
                return this.PhotoField;
            }
            set
            {
                this.PhotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone
        {
            get
            {
                return this.TelephoneField;
            }
            set
            {
                this.TelephoneField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsEmpleados.IEmpleadosSAPService")]
    public interface IEmpleadosSAPService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosSAPService/GetEmpleadoSAP", ReplyAction="http://tempuri.org/IEmpleadosSAPService/GetEmpleadoSAPResponse")]
        System.Threading.Tasks.Task<wsEmpleados.GetEmployeeSAPResponse> GetEmpleadoSAPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosSAPService/GetAnniversariesOfTheWeek", ReplyAction="http://tempuri.org/IEmpleadosSAPService/GetAnniversariesOfTheWeekResponse")]
        System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetAnniversariesOfTheWeekAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosSAPService/GetBirthdaysOfTheWeek", ReplyAction="http://tempuri.org/IEmpleadosSAPService/GetBirthdaysOfTheWeekResponse")]
        System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetBirthdaysOfTheWeekAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosSAPService/GetAnniversariesOfTheMonth", ReplyAction="http://tempuri.org/IEmpleadosSAPService/GetAnniversariesOfTheMonthResponse")]
        System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetAnniversariesOfTheMonthAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosSAPService/GetHiring", ReplyAction="http://tempuri.org/IEmpleadosSAPService/GetHiringResponse")]
        System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetHiringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosSAPService/SearchByCompleteName", ReplyAction="http://tempuri.org/IEmpleadosSAPService/SearchByCompleteNameResponse")]
        System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> SearchByCompleteNameAsync(string strParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosSAPService/SearchByIdNo", ReplyAction="http://tempuri.org/IEmpleadosSAPService/SearchByIdNoResponse")]
        System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> SearchByIdNoAsync(string strParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosSAPService/GetBirthdays", ReplyAction="http://tempuri.org/IEmpleadosSAPService/GetBirthdaysResponse")]
        System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetBirthdaysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosSAPService/GetAnniversaries", ReplyAction="http://tempuri.org/IEmpleadosSAPService/GetAnniversariesResponse")]
        System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetAnniversariesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosSAPService/GetDatosEmpleados", ReplyAction="http://tempuri.org/IEmpleadosSAPService/GetDatosEmpleadosResponse")]
        System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetDatosEmpleadosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IEmpleadosSAPServiceChannel : wsEmpleados.IEmpleadosSAPService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class EmpleadosSAPServiceClient : System.ServiceModel.ClientBase<wsEmpleados.IEmpleadosSAPService>, wsEmpleados.IEmpleadosSAPService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EmpleadosSAPServiceClient() : 
                base(EmpleadosSAPServiceClient.GetDefaultBinding(), EmpleadosSAPServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEmpleadosSAPService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpleadosSAPServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EmpleadosSAPServiceClient.GetBindingForEndpoint(endpointConfiguration), EmpleadosSAPServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpleadosSAPServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EmpleadosSAPServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpleadosSAPServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EmpleadosSAPServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpleadosSAPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<wsEmpleados.GetEmployeeSAPResponse> GetEmpleadoSAPAsync()
        {
            return base.Channel.GetEmpleadoSAPAsync();
        }
        
        public System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetAnniversariesOfTheWeekAsync()
        {
            return base.Channel.GetAnniversariesOfTheWeekAsync();
        }
        
        public System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetBirthdaysOfTheWeekAsync()
        {
            return base.Channel.GetBirthdaysOfTheWeekAsync();
        }
        
        public System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetAnniversariesOfTheMonthAsync()
        {
            return base.Channel.GetAnniversariesOfTheMonthAsync();
        }
        
        public System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetHiringAsync()
        {
            return base.Channel.GetHiringAsync();
        }
        
        public System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> SearchByCompleteNameAsync(string strParam)
        {
            return base.Channel.SearchByCompleteNameAsync(strParam);
        }
        
        public System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> SearchByIdNoAsync(string strParam)
        {
            return base.Channel.SearchByIdNoAsync(strParam);
        }
        
        public System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetBirthdaysAsync()
        {
            return base.Channel.GetBirthdaysAsync();
        }
        
        public System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetAnniversariesAsync()
        {
            return base.Channel.GetAnniversariesAsync();
        }
        
        public System.Threading.Tasks.Task<wsEmpleados.GetEmployeeIntranetResponse> GetDatosEmpleadosAsync()
        {
            return base.Channel.GetDatosEmpleadosAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEmpleadosSAPService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEmpleadosSAPService))
            {
                return new System.ServiceModel.EndpointAddress("http://iissvr/wsEmpleadosSAP/EmpleadosSAP.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EmpleadosSAPServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEmpleadosSAPService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EmpleadosSAPServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEmpleadosSAPService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEmpleadosSAPService,
        }
    }
}
